{
  description = "My personal website, statically generated by Hugo";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    git-hooks.url = "github:cachix/git-hooks.nix";
    git-hooks.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = {
    self,
    nixpkgs,
    flake-utils,
    git-hooks,
  }:
    flake-utils.lib.eachDefaultSystem (system: let
      pkgs = import nixpkgs {inherit system;};
      pre-commit-check = self.checks.${system}.pre-commit-check;
    in {
      checks.pre-commit-check = git-hooks.lib.${system}.run {
        src = ./.;
        hooks = {
          alejandra.enable = true;
          editorconfig-checker.enable = true;
        };
      };
      devShells.default = pkgs.mkShellNoCC {
        inherit (pre-commit-check) shellHook;
        buildInputs = pre-commit-check.enabledPackages;
        inputsFrom = [self.packages.${system}.site];
        env.FOO = "foo";
      };
      formatter = pkgs.alejandra;
      packages = {
        site = pkgs.mkShellNoCC {
          name = "skye-website";
          src = ./.;
          nativeBuildInputs = [
            pkgs.hugo
            pkgs.go
          ];
        };
        default = self.packages.${system}.site;
      };
    });
}
